require('base/columns')
require('base/search')
require('base/tabs')
require('base/other')

require ('keys/main')
require ('keys/plugins')

require('plugins/lazy')
require('plugins/neotree')
require('plugins/treesitter')
require('plugins/lsp')
require('plugins/cmp')
require('plugins/evergarden')
require('plugins/colors')
require('plugins/auto_session')
require('plugins/lualine')
require('plugins/clear')
require('plugins/auto_pairs')
require('plugins/coc')
require('plugins/auto_compiler_cfg')
require('plugins/clangd_extensions')
require('plugins/telescope')
require('plugins/dressing')
require('plugins/finecmd')
require('plugins/toggleterm')

