require('base/columns')
require('base/search')
require('base/tabs')
require('base/other')

require ('keys/main')
require ('keys/plugins')

require('plugins/lazy')
require('plugins/auto_compiler')
require('plugins/colors')
require('plugins/clear')
require('plugins/treesitter')
require('plugins/lsp')
require('plugins/cmp')
require('plugins/mason')
require('plugins/auto_pairs')
require('plugins/clangd_extensions')
require('plugins/coc')
